Modified function 2051, hauls speeds
Eucrow/oab_post_dump pull request #3
Opened 2023-03-23 11:38 UTC by Itxaso68

2023-03-23 12:33 UTC, Eucrow commented on oab_post_dump_haul_characteristics.R
> +  cl <- read.csv("caracteristicas_lances.csv", sep = ";", header = TRUE, na=NA)
Aquí lees el fichero características_lances.csv, pero no es necesario volver a leerlo, porque previamente, en oab_post_dump.R ya se lee y se guarda en la variable caracteristicas_lances. Sin embargo, y no me había dado cuenta hasta ahora, ese caracteristicas_lances debería darse a la función como argumento. ¿Sabrías hacerlo?

2023-03-23 12:37 UTC, Eucrow commented on oab_post_dump_haul_characteristics.R
> +    errors <- addTypeOfError(errors, "WARNING: speed of haul out of range according to master")
Aquí has quitado una parte del código... pero yo creo que está guay la información que da el código original... ¿por qué has decidido quitarlo?

2023-03-23 12:43 UTC, Eucrow commented on oab_post_dump_haul_characteristics.R
> +  errors <- subset(errors,errors$VELOCIDAD>errors$VELOCIDAD_MAX | errors$VELOCIDAD<errors$VELOCIDAD_MIN, )
No tengo apenas experiencia con los subsets... pero me mosquea que despues de errors$VELOCIDAD_MIN haya una coma. ¿Sabes por qué es esa coma? :)

2023-03-23 12:45 UTC, Eucrow requested changes
Te he dejado unos comentarios, creo que puedes contestarlos desde aquí...

2023-03-23 13:03 UTC, Itxaso68 commented on oab_post_dump_haul_characteristics.R
> +  cl <- read.csv("caracteristicas_lances.csv", sep = ";", header = TRUE, na=NA)
Voy a intentar...

2023-04-04 13:19 UTC, Itxaso68 commented on oab_post_dump_haul_characteristics.R
> +  cl <- read.csv("caracteristicas_lances.csv", sep = ";", header = TRUE, na=NA)
Creo que envié este de nuevo pero modificado, por tu indicación de que ya se leía el fichero: caracteristicas_lances.csv

2023-04-04 13:28 UTC, Itxaso68 commented on oab_post_dump_haul_characteristics.R
> +  errors <- subset(errors,errors$VELOCIDAD>errors$VELOCIDAD_MAX | errors$VELOCIDAD<errors$VELOCIDAD_MIN, )
Esa coma no pinta nada, no sé como se me coló. Pero acabo de correr ese scipt ( con la coma) y con un error generado, y hace bien la función. Pero pintar, no pinta nada

2023-04-04 13:32 UTC, Itxaso68 commented on oab_post_dump_haul_characteristics.R
> +  errors <- subset(errors,errors$VELOCIDAD>errors$VELOCIDAD_MAX | errors$VELOCIDAD<errors$VELOCIDAD_MIN, )
En próximos envios, aparecerá esta coma fuera

2023-04-04 13:38 UTC, Itxaso68 commented on oab_post_dump_haul_characteristics.R
> +    errors <- addTypeOfError(errors, "WARNING: speed of haul out of range according to master")
Pues, busqué la información del código original, y no sé: o no busque bien o no encontré a que parte del código te refieres

2023-04-04 13:40 UTC, Itxaso68 commented on oab_post_dump_haul_characteristics.R
> +  cl <- read.csv("caracteristicas_lances.csv", sep = ";", header = TRUE, na=NA)
Como soy muy original le llamé " New modified function2051, hauls speed"

2024-04-11 10:25 UTC, closed without merging